### ISSUE TITLE
[feature]: Add shortcut buttons to the navbar (edited)

### ISSUE THREAD

**Issue by qtvr01** [dvcol/synology-download#102]
I hope you can delete the completed file from the first screen like other download station programs.

**Comment by dvcolomban** [comment]
Hello, 

If you just want to filter completed download tasks, you can adjust which status are visible for each tab in the settings menu:

![Screenshot 2022-04-12 at 19 05 40](https://user-images.githubusercontent.com/90617742/163016577-06a0b3a3-859b-49e4-ad1c-a68283795aa4.png)

If you mean clearing download task from the remote server (the diskstation itself) similarly to this button:

![Screenshot 2022-04-12 at 19 07 50](https://user-images.githubusercontent.com/90617742/163016700-6a9d0826-86b8-445a-be51-c181206dc82b.png)

Then, it could be implemented, but that would mean that notifying that task have completed or seing what has finished might be more difficult to see.

I might implements an optional settings for the next release.

**Comment by qtvr01** [comment]
![1233333333](https://user-images.githubusercontent.com/89171748/163105639-16151de1-d0bb-43d7-b00b-e29d99b79280.jpg)

If you look at the other program, nas download manager, there is a function that can delete the completed file immediately like a red circle, so I want you to implement it.

I hope it's realized like this.

![1233333333333333333333](https://user-images.githubusercontent.com/89171748/163106071-b7622629-5056-4d1b-9caf-29bcdc00392d.jpg)





> Hello,
> 
> If you just want to filter completed download tasks, you can adjust which status are visible for each tab in the settings menu:
> 
> ![Screenshot 2022-04-12 at 19 05 40](https://user-images.githubusercontent.com/90617742/163016577-06a0b3a3-859b-49e4-ad1c-a68283795aa4.png)
> 
> If you mean clearing download task from the remote server (the diskstation itself) similarly to this button:
> 
> ![Screenshot 2022-04-12 at 19 07 50](https://user-images.githubusercontent.com/90617742/163016700-6a9d0826-86b8-445a-be51-c181206dc82b.png)
> 
> Then, it could be implemented, but that would mean that notifying that task have completed or seing what has finished might be more difficult to see.
> 
> I might implements an optional settings for the next release.



> Hello,
> 
> If you just want to filter completed download tasks, you can adjust which status are visible for each tab in the settings menu:
> 
> ![Screenshot 2022-04-12 at 19 05 40](https://user-images.githubusercontent.com/90617742/163016577-06a0b3a3-859b-49e4-ad1c-a68283795aa4.png)
> 
> If you mean clearing download task from the remote server (the diskstation itself) similarly to this button:
> 
> ![Screenshot 2022-04-12 at 19 07 50](https://user-images.githubusercontent.com/90617742/163016700-6a9d0826-86b8-445a-be51-c181206dc82b.png)
> 
> Then, it could be implemented, but that would mean that notifying that task have completed or seing what has finished might be more difficult to see.
> 
> I might implements an optional settings for the next release.

**Comment by dvcol** [comment]
Ok, then this button already does exactly the same:

![image](https://user-images.githubusercontent.com/17250935/163165972-1db178f9-93f6-4fa3-ae37-b710205f99ef.png)

I don't plan to add to the toolbar for now as it restricts usable space for tabs with many filters sorry.

**Comment by dvcol** [comment]
If this functionality doesn't behave as the expected behaviour (clearing all finished task from the station), please open a bug ticket with as much information to reproduce as possible (DSM version, example file, error log, etc.).

And if you enjoy the application, please leave a review on the chrome webstore, it is always appreciated :)

**Comment by qtvr01** [comment]
I am not good at English, so I wrote it using a translator, so please understand if it's a little awkward.

I know it has the same functionality.
However, it is a function that you press the most when you use the program, so I made an opinion because it is placed on the top or bottom of the first screen so that you can use it more comfortably.

Do you have any plans to let me input http and https directly?
I heard that the program I used before was forced by Chrome to https, so http disappeared and it was quite difficult to maintain the certificate.

Anyway, thank you for making a very good program.


> Ok, then this button already does exactly the same:
> 
> ![image](https://user-images.githubusercontent.com/17250935/163165972-1db178f9-93f6-4fa3-ae37-b710205f99ef.png)
> 
> I don't plan to add to the toolbar for now as it restricts usable space for tabs with many filters sorry.

**Comment by dvcol** [comment]
Ok, I understand your request a little bit better know. 

I pushed a new version with optional shortcut buttons in the navbar (but only for actions already supported in the current dropdown menu).

It'll be available in the next release (maybe a few days).

**Comment by qtvr01** [comment]
Thank you for making a button.

However, regarding http, other programs were supposed to choose http and https like that, but one day, because of the Chrome Webstore policy, it was changed to write https only because http could not be supported.

![Screenshot 2022-04-14 at 21 55 16](https://user-images.githubusercontent.com/89171748/163395189-2ec142e2-9692-47a2-b447-1f73eb554e40.jpg)

If you need to apply the same policy later, I would rather let you input the protocol yourself.

![1222222222222222222222](https://user-images.githubusercontent.com/89171748/163395363-5c8d45f7-6286-4429-9b58-9b013861ae98.jpg)

> Ok, I understand your request a little bit better know.
> 
> I pushed a new version with optional shortcut buttons in the navbar (but only for actions already supported in the current dropdown menu).
> 
> It'll be available in the next release (maybe a few days).
> 
> > Do you have any plans to let me input http and https directly?
> > I heard that the program I used before was forced by Chrome to https, so http disappeared and it was quite difficult to maintain the certificate.

> 
> The application currently supports both http and https for logins here: ![image](https://user-images.githubusercontent.com/17250935/163382403-26a759c4-7e45-4887-87ae-a7532fbfd91c.png)
> 
> If it doesn't for your, please fill a separate bug report on it :)

**Comment by dvcol** [comment]
Hey again, 

I understand your wariness, but supporting other protocols like ftp or sftp is not trivial and would mean significant effort beyond what is done for http and https.

Moreover to increase ease of use and as an additional safeguard against malformed url, i don't plan to implement more permissive login form.
