### ISSUE TITLE
[bug]: "Logged in session doesn't have permission" error for 5-10 minutes after first startup

### ISSUE THREAD

**Issue by foxmajik** [dvcol/synology-download#106]
### Description

After a successful login, no content is populated in task tabs; attempting to refresh returns error "Logged in session doesn't have permission" (or something like that -- I don't remember the exact error and I can't replicate it now).

After 5-10 minutes the content refreshed on its own and the addon started working normally.

Platform is Chrome 64bit on Windows 11.

### Affected part

Which part of the application is impacted

- [x ] General UI
- [ ] General Options/Settings
- [ ] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

### Screenshots or Mock up

If possible provide a screenshot or a mock-up of the issue.

### Steps to Reproduce the Issue

1. Install addon
2. Log in
3. Nothing appears in the task tabs
4. Click refresh icon
5. Error.

### Failure Logs

```
If possible open the console by right clicking the extension's icon, left clicking on 'Inspect Popup-up' and then copy pasting any error log you can find.
```

^My browser doesn't have "inspect popup-up" [sic]

### Versions

**Extension version**: (visible the manage extension page in your browser)

1.14.2

**Browser version**: (usually found in the browser's "About")

100.0.4896.88

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)

DSM 7.0.1-42218 Update 3

**Comment by dvcol** [comment]
Hi, thanks you for posting a ticket !

I didn't encounter this issue before, is this happening every login attempt ?

Is the error the following message  ? 

`105: 'The logged in session does not have permission'`

If so, this is a Synology error, it might mean the account attempting to login, or fetching has too restricted access rights to your DiskStation.

By any chance had the permission for you account been recently changed prior to encountering this error ?
