### ISSUE TITLE
The logged in session does not have permission

### ISSUE THREAD

**Issue by thetimelordsofgallifrey** [dvcol/synology-download#118]
Hi

I'm trying to use your app, I log in to my account without issues, but as soon as I try to do anything I get 'The logged in session does not have permission'  I can't work out what permission I need to set.

Man thanks
Simon
![Screenshot 2022-06-21 110641](https://user-images.githubusercontent.com/44099531/174774620-44ec928d-5273-4731-936b-10bdcd23ff1f.jpg)
n

**Comment by dvcol** [comment]
Hi,

It looks like an issue on you diskstation config.
The login session must not have all the appropriate permission to acess the download station API.

Make sure that in your control panel > user & Group > <user or group name > Applications both DownloadStation and File Station have allow permission.

Similarly, you should make sure your user has read/write permission to the target folder destination.

![image](https://user-images.githubusercontent.com/17250935/175770257-8f1a16d5-8639-4c05-928e-ee4df7d4926d.png)

**Comment by PRK40** [comment]
I have added those permissions.  I am not sure about the target folder destination.  Was I supposed to set one up when I installed the extension?
