### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by PRK40** [dvcol/synology-download#124]
I can only login after I've accessed the DiskStation web interface. All attempts prior to logging into the web interface fail.  After I've logged in, I can then log in to the extension.

**Comment by dvcol** [comment]
Do you use https to login ? 

If so this might be the cause, chrome needs an ovveride by the user to fetch on unsecure urls.

Alternatively you can also add SYnology's certificate to secure the connection.

Hopes that helps
