### ISSUE TITLE
[bug]: Can not select port 443 in configuration

### ISSUE THREAD

**Issue by Vad1mo** [dvcol/synology-download#126]
### Description

When selecting a pot all ports lower the 4 numbers eg. 443 arre marked as not possible 

<img width="789" alt="Bildschirmfoto 2022-08-14 um 20 07 05" src="https://user-images.githubusercontent.com/1492007/184549437-9e810906-fb9f-4d29-89b2-f708676b9f8b.png">

### Affected part

Which part of the application is impacted

- [x] General UI
- [x] General Options/Settings
- [x] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

### Screenshots or Mock up

If possible provide a screenshot or a mock-up of the issue.

### Steps to Reproduce the Issue

1. try setting port 443

**Comment by dvcol** [comment]
Hello, priviledge ports can now be used in credentials. A warning will be shown but it can be overriden. 

Hopes that helps :)

**Comment by dvcol** [comment]
If you enjoy the extension, please leave a review in the webstore, it helps with discovery :)
