### ISSUE TITLE
[feature]: Support for URLs other than Magnets via Context Menu

### ISSUE THREAD

**Issue by dlfiz** [dvcol/synology-download#137]
Which part of the application do you with to improve

- [ ] General UI
- [ ] General Options/Settings
- [ ] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [X] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

**Comment by dvcol** [comment]
Contest menu already supports forwarding non magnet links.

If you meant quick menu (dropdown), the latest release contains an experimental attempt at doing so (see [release](https://github.com/dvcol/synology-download/releases/tag/v1.16.0))

**Comment by dlfiz** [comment]
Thanks for this, I can see the intercept option. Unfortunately for the
torrent site i'm using it just throws a login.php error. I assume this is
because it's not a magnet link.

**Comment by dvcolomban** [comment]
If you use the context menu it can only forward links, you need to either use the quick menu (drop down on click) or to download locally the file (trhough chrome native download) which will be intercepted if intercept is enabled.

![image](https://user-images.githubusercontent.com/90617742/225316554-071ed1f3-d7c7-4845-a78a-11213098dc9e.png)


![image](https://user-images.githubusercontent.com/90617742/225316922-bc272b0d-83df-4fc6-9456-d30012626c6f.png)


Note however that if the iste uses multiple redirect/login check, or if unsafe confirmation prompt from chrome is required, it might fail.

**Comment by dvcolomban** [comment]
Hope it helps ! 

By the way, if you'are enjoying the extension, please leave a review on the store, it helps with discovery :)

**Comment by dlfiz** [comment]
Thanks for your help. It appears perhaps the site uses multiple checks as
the parsing still fails on login.php. Nevertheless a great extension
thanks.

**Comment by dlfiz** [comment]
Also just thought I'd share, this plugin
https://chrome.google.com/webstore/detail/nas-download-manager-for/iaijiochiiocodhamehbpmdlobhgghgi?hl=en
is working OK with the intercept from context menu - no login.php error.
Cheers
