### ISSUE TITLE
[bug]: Login attempt failed

### ISSUE THREAD

**Issue by i3kevin** [dvcol/synology-download#144]
### Description

Tried to log in via extension, display "Login attempt failed: Permission denied".

The account works fine if login via DSM web UI. 

Checked the following permission is allowed.

1. Control panel > user & Group > Applications both DownloadStation and File Station have allow permission.
2. User has read/write permission to the target folder destination.

### Affected part

Which part of the application is impacted

- [ ] General UI
- [ ] General Options/Settings
- [ x ] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

### Screenshots or Mock up

![image](https://user-images.githubusercontent.com/45218158/197534246-a7129dc3-871f-43b5-ab4b-71569751d1a8.png)

### Versions

**Extension version**: 1.14.6

**Browser version**: 106.0.5249.103 

**DSM version**: DSM 7.1-42661 Update 3

**Comment by dvcol** [comment]
For some reason it seems that non-administrators account have permission issuew when loging to download station.

I've had the issue with locacl account on my side to, but i'm not sure what is the missing permission in DSM.
