### ISSUE TITLE
[feature]: torrent files upload

### ISSUE THREAD

**Issue by cheetah3k5** [dvcol/synology-download#146]
Hello and thank you for this great plugin. I was wondering if there is a possibility to add torrent files from a computer, instead of just 
url or magnet link. I am asking because I am having problems adding downloads from private trackers. Instead of adding the download task, it just downloads a file called login.php. I have tried using credentials but with no luck. 

### Description

A brief description of the proposed functionality.

### Affected part

Which part of the application do you with to improve

- [ ] General UI
- [ ] General Options/Settings
- [ ] Connection settings
- [ ] Task list
- [ ] Notification
- [ ] Pop-up
- [ ] Context-menu
- [ ] Content-script (inside the page)
- [ ] Overlay

### Screenshots or Mock up

If possible provide a screenshot or a mock-up of the desired functionality.

### Code example

```
If you have a specific solution in mind, please document it here, or better create a PR and link it to this issue.
```

**Comment by dvcol** [comment]
Done in release [2.0.2](https://github.com/dvcol/synology-download/releases/tag/v2.0.2).

note that you can also intercept download (alpha support so might be buggy) too now.

**Comment by dvcol** [comment]
If you enjoy the extension, please leave a review in the webstore, it helps with discovery :)
