### ISSUE TITLE
Failed to create download task

### ISSUE THREAD

**Issue by Kit-Leung** [dvcol/synology-download#157]
Failed to create download task to me ,I guess it was failed to find or load the destination folder , tried to "Change default destination folder" , but stopped looping the "Loading folder content" notice, thanks for your help!

**Comment by m1r0n41k** [comment]
Have the same issue with my DS923+
<img width="701" alt="Screenshot 2023-02-24 at 00 36 51" src="https://user-images.githubusercontent.com/10367917/221046349-41aa6fb1-eaf0-4dc9-9c38-c46a38c21ddc.png">
