### ISSUE TITLE
[bug]: Logged in user unable to fetch folders or customize folders in Context Menu

### ISSUE THREAD

**Issue by mefixxx** [dvcol/synology-download#210]
### Affected part

Connection (login/fetching)

### Extension version

3.6.0

### DSM version

DSM 7.1.1-42962 Update 5

### Browser version

Chrome 112.0.5615.138

### Description

After successfully logging in using either admin/custom/dedicated extension user
<img width="177" alt="image" src="https://github.com/dvcol/synology-download/assets/26686865/92a3a1da-8553-4feb-bfd8-77856d011019">
extension fails to load folders when attempting to interact with magnet links or attempting to customize context menu options
<img width="181" alt="image" src="https://github.com/dvcol/synology-download/assets/26686865/5ad09855-169b-4ff2-949f-6c7c12ef0259">

Note: Normal download management in browser is disabled (why is it even there)

### Steps to Reproduce the Issue

Successfully Log in with credentials
Attempt to enable Custom Folder in Context menu.

### Failure Logs

```console
[{"timestamp":"2023-06-03T13:27:28.632Z","level":4,"source":"background","value":"Polling service failed to fetch list","params":"Error: The logged in session does not have permission"},{"timestamp":"2023-06-03T13:27:28.712Z","level":4,"source":"background","value":"Polling service failed to fetch statistics","params":"Error: The logged in session does not have permission"},{"timestamp":"2023-06-03T13:27:29.954Z","level":4,"source":"option","value":"Failed load folders.","params":"Error: Invalid session."}]
```

**Comment by dvcol** [comment]
Hello,

From what the log seems to indicate, the issue seems to come from the Synology session rights.

For the custom destination modal, you need to have a session with read/write access to FileStation, not just DownloadStation.

![image](https://github.com/dvcol/synology-download/assets/17250935/4f425055-edeb-4817-8742-f843c463bd43)

Can you check if this is the case ?

Note that the extension sues cookie session ID so if you have an open session on the same domain with lesser permission, it might prevent full fonctionalities

**Comment by dvcol** [comment]
`
Note: Normal download management in browser is disabled (why is it even there)
`

This should have no impact, it just mean you won't be abale to redirect local download to the diskstation or intercept local download automatically

**Comment by mefixxx** [comment]
Yeah it did have permissions for both file station and downloaded station.
I ended up fixing it by giving it permissions not only to the destination subfolder of the volume but to the entire volume itself.
Running smoothly now! Ty!

**Comment by jwmann** [comment]
I had this issue and all my permissions were correct.

_**The way I fixed it**_:

1) Go to Extension Settings -> Connection -> Credientials
2) Click "Logout"
3) Once logged out. Click "Login"

That's it 😕
