### ISSUE TITLE
[Support]: Failed to load folder. The requested API does not exist.

### ISSUE THREAD

**Issue by zitzman** [dvcol/synology-download#212]
### Affected part

General Options/Settings, Connection (login/fetching)

### Extension version

3.6.0

### DSM version

SRM 1.3.1-9346 Update 5

### Browser version

Chrome 115.0.5790.110 (Official Build) (64-bit)

### Description

I get an error whenever I try to create a task.
Does this extension work on the Synology RT6600ax?
Test Login Works.

### Steps to Reproduce the Issue

1. Click on extension icon
2. Create Task

### Screenshots or Mock up

![image](https://github.com/dvcol/synology-download/assets/1789368/8a7fecc6-308f-489a-8d2a-4be96e4cd17d)
![image](https://github.com/dvcol/synology-download/assets/1789368/ac4a33dd-5841-483b-89d9-5bdfbe8fe6c6)

### Failure Logs

```console
popup.entry.js:242 [2023-07-27T22:25:55.109Z - popup] Failed load folders. Error: The requested API does not exist
    at popup.entry.js:242:65393
    at popup.entry.js:234:28183
    at l._next (popup.entry.js:234:24748)
    at t.next (popup.entry.js:234:14600)
    at popup.entry.js:242:129211
```

**Comment by dvcol** [comment]
Hello, I'm not familiar wih this particular synology nas (seems to be a router too right ?).

For this extension to work you need to have both [file station ](https://www.synology.com/en-global/dsm/packages/FileStation)and [download station ](https://www.synology.com/fr-fr/dsm/packages/DownloadStation) installed.

The error message seems to indicate that the APIs for disk station are not present, to verify this, you can look at the api list in your extension settings (under `Advanced > Storage > Store`)

![image](https://github.com/dvcol/synology-download/assets/17250935/1327e0fd-8e58-4347-993f-4381cd0dd120)

If you don't find both endpoints `SYNO. DownloadStation2 `and `SYNO.FileStation`, then either your device doesn't support file and download station or you need to install it.

Hope it helps :)
