### ISSUE TITLE
[bug]: Qc login failed, requesting a solution

### ISSUE THREAD

**Issue by longjs0424** [dvcol/synology-download#214]
### Affected part

Connection (login/fetching)

### Extension version

3.91

### DSM version

Dsm 7.2

### Browser version

 Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36 Edg/117.0.0.0

### Description

Dsm 7.2 Qc login failed

### Steps to Reproduce the Issue

Dsm 7.2 Qc login failed

### Screenshots or Mock up

![image](https://github.com/dvcol/synology-download/assets/56985565/693f8047-2d83-4e72-89d2-ceab08d6ea70)

**Comment by nbartley** [comment]
I am seeing this as well. Direct connect to 5000/5001 and attempt to log in, this result. Direct connect to downloadstation 8000/8001 ports, no problem.

**Comment by GAPP99** [comment]
Same for me.

**Comment by GAPP99** [comment]
> I am seeing this as well. Direct connect to 5000/5001 and attempt to log in, this result. Direct connect to downloadstation 8000/8001 ports, no problem.

Can you explain what you did from within the extension?

**Comment by dvcol** [comment]
Hello, as mentioned in [this issue](https://github.com/dvcol/synology-download/issues/218), QC login uses dynamic url from synology's side, and we cannot discover this url change dynamically.

You'll need to login to the web UI manually and use the newly generated url to make the extension work.

For this reason, we recommend using either local uri when possible or secured port forwarding when remotely accessing
