### ISSUE TITLE
[bug]: Bug Report (please change this title)

### ISSUE THREAD

**Issue by GAPP99** [dvcol/synology-download#218]
### Affected part

Connection (login/fetching)

### Extension version

3.10.0

### DSM version

DSM 7.1.1

### Browser version

Version 117.0.5938.150 (Officiel version) (64-bit)

### Description

The chrome extension used to work, but for whatever reason it won't log in any more. I put in the login details, and it gives me this error: 

Manual login is required.
Auto-login failed with error:
Unexpected token '<', "<!doctype "... is not valid JSON

### Steps to Reproduce the Issue

1. Go into settings
2. Select Quick connect, and input the details.
3. Click Save or Test login.

### Screenshots or Mock up

https://prnt.sc/nLDSHYA1QwSj

### Failure Logs

```console
<div class="MuiBox-root css-ti4njy">Manual login is required.</div>
```

**Comment by dvcol** [comment]
From the error message, it seems that the quick-connect endpoint doesn't return the api.

As noted in the login session, quick-connect url change dynamically on synology side and it doesn't provide a easy url follow scheme to discover those new url.

If you use quick-connect, you'll need to login manually and update the url manually again.
