### ISSUE TITLE
[feature]: Clicking the Folders of the Default Location should Navigate you to the Location

### ISSUE THREAD

**Issue by jwmann** [dvcol/synology-download#225]
### Affected part

General UI, General Options/Settings, Quick menus (dropdown click), Local Downloads

### Description

Right now, you have the option to set a Default Location, and this works great.
If you don't select a location it'll download to the default setting: e.g. (`/Volume1/MyDirectory/MyDefaultLocation`)

However, if you select a new Location. Clicking the Directory from the listed default location, should bring you to that location.
Right now it does nothing.

### Screenshots or Mock up

https://github.com/dvcol/synology-download/assets/436270/314b95c7-83aa-47b5-bc69-edebcd0b0d10

**Comment by dvcol** [comment]
Yes, the current tree traversal is very rudimental (I got lazy on reworking leaf/branch navigation).

Resolving nested path from top or sibling requires a significant rework of the whole state system in the file explorer, It would be nice, but I don't know when I would have the time to look into it.

If someone is interested in working on it, the relevant code is [here](https://github.com/dvcol/synology-download/blob/main/src/components/common/explorer/folder/explorer.tsx), but it's a bit of a spaghetti code.

IMO it should be fully re-written and use virtual scrolling like mentioned in [this issue](https://github.com/dvcol/synology-download/issues/38)

**Comment by dvcol** [comment]
It should be somewhat implemented in the next release.

Might be a bit buggy still if the connection is slow, so YMMV

**Comment by jwmann** [comment]
> It should be somewhat implemented in the next release.
> 
> Might be a bit buggy still if the connection is slow, so YMMV

It works great! Thank you so much 🙌
