### ISSUE TITLE
[bug]: Scrollbars always shown

### ISSUE THREAD

**Issue by wpigoury** [dvcol/synology-download#226]
### Affected part

General UI

### Extension version

3.10.6

### DSM version

DSM 7.2.1

### Browser version

Chrome Version 123.0.6312.86 (Official build) (64 bits)

### Description

The popup always has scrollbars shown on the right and at the bottom, whatever the screen displayed or the browser window size.
I first noticed it in 3.10.5 but still present in 3.10.6.
Note that issue is present on Brave as well Version 1.64.109 Chromium: 123.0.6312.58 (Official build) (64 bits).

### Steps to Reproduce the Issue

1. Open the popup
2. See scrollbars

### Screenshots or Mock up

![scrollbars](https://github.com/dvcol/synology-download/assets/6941240/b99d94cd-4328-4e74-9824-d59bc4c4b10c)

**Comment by dvcol** [comment]
Hello,

In the last release I dynamically set the popup size based on window size to fix an issue on mac, this might have introduced a regression.

- What OS do you use, mac (intel / apple silicon), windows or linux ?

- Also, could you run this in the popup console (right-click on the popup or the icon) ?

![image](https://github.com/dvcol/synology-download/assets/17250935/b35d92e2-af78-496e-a4cd-12de10f1da69)

container = document.querySelector('#synology-download-popup-app-container')

```
console.info({
	container:{
		width: container.style.width,
		height: container.style.height,
	},
	window: {
		width: window.innerWidth,
		height: window.innerHeight
	}
})
```

And report back the results ?

It should output something like this:

![image](https://github.com/dvcol/synology-download/assets/17250935/ff255e3f-ed06-4a8c-bd15-8783a9a25ab2)

**Comment by dvcol** [comment]
From what I gather, chrome doesn't respect the same window size maximums in Windows and macOS, leading to this overflow behaviour.

Can you run this to check if it fixes it (I don't have a Windows machine at the moment sadly 😅)?

```js
container = document.querySelector('#synology-download-popup-app-container');
const log = () => console.info({
	container:{
		width: container.clientWidth,
		height: container.clientHeight
	},
	window: {
		width: window.innerWidth,
		height: window.innerHeight
	}
})

log();

container.style.maxWidth = '720px'
container.style.maxHeight = '592px'

log();
```

Additionally, it would be greatly appreciated if you could check until increasing `maxWidth` and `maxHeight` triggers the vertical/horizontal `scrollbars`.

(729x592 was the previously hardcoded values, but I don't remember how I got them previously)

**Comment by wpigoury** [comment]
This does fix the issue:
![image](https://github.com/dvcol/synology-download/assets/6941240/6575dbe5-1e55-4fcb-bbbd-5ad5a68d1da5)

Though I cannot find out which value starts to trigger the scrollbars, at least not with that method as whatever the value I set for maxWidth and maxHeight, it just resizes the popup properly to the right size.

**Comment by dvcol** [comment]
Let's cap to this resolution for windows then, at worst it will just be a little less flexible than it could be, but it's not worse than before 🤷 .

**Comment by dvcol** [comment]
3.10.7 should be published on the chromestore :)
