### ISSUE TITLE
[feature] Can the "Port" value be set to "optional" ?

### ISSUE THREAD

**Issue by Majesty00** [dvcol/synology-download#229]
### Affected part

Connection (login/fetching)

### Description

I'm using nginx proxy manager and the port is already configured there for my Synology NAS. I can't use my own DNS to log in your app (because it appends the port to my DNS so, it creates something like **nas.domain.duckdns.org_:5001_:5001**). The characters between _ are already known by nginx proxy manager.

I'm not sure I'm clear (or maybe I don't know how to use nginx proxy manager properly).

It's good to know that your app is still being updated! :)

Thank you!

**Comment by dvcol** [comment]
I've pushed a small update that should allow a custom URL scheme in the connection field.

Not sure it won't have any side effects though, as the code base has grown quite big and I don't have the time currently to do heavy testing.

You can pick up the latest release to try it out, or it should hit the webstore shortly.

Note that if you use https through proxy, the connection can be a bit unstable if the SSL certificate is not correctly set up on your machine & NAS.
