### ISSUE TITLE
[bug]: Cannot add ed2k links

### ISSUE THREAD

**Issue by wpigoury** [dvcol/synology-download#232]
### Affected part

Other (none of the above)

### Extension version

3.16.1

### DSM version

DSM 7.2.1-69057 Update 5

### Browser version

130.0.6723.92 (Build officiel)

### Description

It's been roughly one week that I cannot add ed2k links anymore.
The links in the pages are recognized, the submenu is displayed, but when I add to download I get an error message.
Same message appear if I create a custom task and copy/paste the link.
Also in the console I see below errors, not sure if they were here before:
`Uncaught (in promise) Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.`
`Unchecked runtime.lastError: The page keeping the extension port is moved into back/forward cache, so the message channel is closed.`

Adding the link directly in DownloadStation works as expected.

### Steps to Reproduce the Issue

1. Go to a page with ed2k links
2. Click on a ed2k link and select download destination
3. Error pops in, failing to add the task

or

1. Add download task
2. Paste the ed2k link
3. Click on Create
4. Error pops in, failing to add the task

### Screenshots or Mock up

![image](https://github.com/user-attachments/assets/b9d29611-2fe4-4d12-bdc8-1d47ad93a825)

### Failure Logs

```console
background.entry.js:1 Uncaught (in promise) Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.Understand this errorAI
Unchecked runtime.lastError: The page keeping the extension port is moved into back/forward cache, so the message channel is closed.
```

### Store snapshots

```json
{
    "state": {
        "logged": true,
        "sid": "",
        "modal": {
            "popup": false,
            "option": true,
            "standalone": false
        },
        "content": {
            "menu": false,
            "dialog": false
        },
        "loading": 1,
        "badge": {},
        "history": {
            "destinations": ["downloads"],
            "folders": [],
            "logs": []
        },
        "download": {
            "enabled": true,
            "defaultFolder": "downloads"
        },
        "api": {},
        "count": {
            "badge": 1,
            "total": 1,
            "tabs": {
                "all": 1,
                "active": 1,
                "inactive": 0,
                "completed": 0,
                "downloads": 0
            }
        }
    },
    "navbar": {},
    "tasks": {
        "taskForm": {},
        "stopping": {},
        "tasks": {}
        },
        "tasksIds": [],
        "files": {},
        "filesIds": {},
        "stats": {
            "emule_speed_download": 0,
            "emule_speed_upload": 0,
            "speed_download": 0,
            "speed_upload": 0
        }
    },
    "downloads": {
        "entities": []
    },
    "scraped": {
        "page": {},
        "contents": {}
    },
    "settings": {
        "notifications": {
            "count": {
                "enabled": true,
                "template": "all",
                "status": ["downloading", "paused", "error", "seeding", "waiting", "extracting", "finishing", "finished", "hash_checking", "filehosting_waiting", "downloading_in_progress", "paused_in_progress", "error_interrupted", "cancelled_interrupted", "finished_complete", "finished_deleted"],
                "destination": {
                    "enabled": false
                },
                "color": "#4285f4"
            },
            "snack": {
                "enabled": true,
                "level": 0,
                "scope": {
                    "popup": true,
                    "content": true
                },
                "timeout": 5000,
                "position": {
                    "vertical": "top",
                    "horizontal": "right"
                }
            },
            "banner": {
                "enabled": true,
                "level": 0,
                "scope": {
                    "background": true,
                    "popup": true,
                    "finished": true,
                    "failed": true
                }
            }
        },
        "connection": {
            "type": "local",
            "authVersion": 7,
            "username": "",
            "password": "",
            "otp_code": "",
            "enable_device_token": false,
            "device_name": "Download Station Client",
            "device_id": "",
            "rememberMe": true,
            "autoLogin": true,
            "protocol": "https",
            "path": "",
            "port": 5001
        },
        "polling": {
            "enabled": true,
            "background": {
                "enabled": true,
                "interval": 20000
            },
            "popup": {
                "enabled": true,
                "interval": 3000
            }
        },
        "tabs": [{
                "id": "48245c70-ca79-4e90-a77a-957f38d3cd94",
                "name": "all",
                "template": "all",
                "status": ["downloading", "paused", "error", "seeding", "waiting", "extracting", "finishing", "finished", "hash_checking", "filehosting_waiting"],
                "destination": {
                    "enabled": false
                },
                "color": "primary"
            }, {
                "id": "3a45b86d-6383-414e-bd7f-1de411b2aa34",
                "name": "active",
                "template": "active",
                "status": ["downloading", "finishing", "hash_checking", "extracting", "seeding"],
                "destination": {
                    "enabled": false
                },
                "color": "secondary"
            }, {
                "id": "47d97f4b-9ae5-45d2-997b-a198008528c7",
                "name": "inactive",
                "template": "inactive",
                "status": ["waiting", "filehosting_waiting", "paused", "error"],
                "destination": {
                    "enabled": false
                },
                "color": "warning"
            }, {
                "id": "6fd7dc36-eb8e-47bf-9093-981244531d59",
                "name": "completed",
                "template": "completed",
                "status": ["finished"],
                "destination": {
                    "enabled": false
                },
                "color": "success"
            }, {
                "id": "452e77af-2c50-443f-91aa-e396534eac5b",
                "name": "downloads",
                "template": "downloads",
                "status": ["downloading_in_progress", "paused_in_progress", "error_interrupted", "cancelled_interrupted", "finished_complete", "finished_deleted"],
                "destination": {
                    "enabled": false
                },
                "color": "secondary"
            }
        ],
        "menus": [{
                "id": "3ca675ba-e048-4b52-b0f4-a463d8d82bf9",
                "title": "Add to Synology Diskstation",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": false,
                "destination": {
                    "custom": false,
                    "path": ""
                }
            }, {
                "id": "a8904ed5-3bbf-42e8-98de-751255a84098",
                "title": "Add to TV",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/tv"
                }
            }, {
                "id": "507f89e4-89dc-46bb-b71d-758293f9e819",
                "title": "Add to Movies",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/movies"
                }
            }, {
                "id": "c1a7637a-b609-4848-8dad-f818b2add4d5",
                "title": "Add to Audiobooks",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/books"
                }
            }, {
                "id": "91d27fd8-fc87-4d1e-8299-0543dcba50fa",
                "title": "Add to Games",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/games"
                }
            }, {
                "id": "a88486aa-659c-4012-b5fa-11f29183425b",
                "title": "Add to BDs",
                "contexts": ["link", "audio", "video", "image", "selection"],
                "modal": true,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/comics"
                }
            }
        ],
        "quick": [{
                "id": "3dd2a25b-8444-4cf7-b977-dd04745a9242",
                "title": "Send to Synology",
                "icon": "server",
                "modal": false,
                "destination": {
                    "custom": false
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "ab15c38d-4aac-44e1-951d-38a91d099eac",
                "title": "Open custom modal",
                "icon": "server",
                "modal": true,
                "destination": {
                    "custom": false
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "af5e0fa8-474b-49de-9a94-9be8c1078dcd",
                "title": "Recent destinations",
                "icon": "history",
                "modal": false,
                "destination": {
                    "custom": false
                },
                "max": 5,
                "type": "recent"
            }, {
                "id": "d6c5a59b-b4cf-48bd-b959-c868f2081372",
                "title": "Save to disk (local)",
                "icon": "download",
                "modal": false,
                "destination": {
                    "custom": false
                },
                "max": 5,
                "type": "download"
            }, {
                "id": "4aafdd45-72e3-47c7-a3d2-d60d241a722c",
                "title": "Recent folders (local)",
                "icon": "historyAlt",
                "modal": false,
                "destination": {
                    "custom": false
                },
                "max": 5,
                "type": "recent_download"
            }, {
                "id": "b8604ff7-e1da-4744-b080-91ff5e057bf0",
                "title": "Send to TV",
                "icon": "video",
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/tv"
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "b3cf32c9-ce11-4e35-98a4-fc6cc74fd149",
                "title": "Send to Movies",
                "icon": "video",
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/movies"
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "82298d23-de04-47d6-a1d8-4c57c33ed7cd",
                "title": "Send to Audiobooks",
                "icon": "musicLibrary",
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/books"
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "63f5fb92-22f7-406b-9639-c13ae5d5e0f6",
                "title": "Send to Games",
                "icon": "game",
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/games"
                },
                "max": 5,
                "type": "task"
            }, {
                "id": "2b8934e4-2cea-4bca-bdb8-8098052a702f",
                "title": "Send to BDs",
                "icon": "photo",
                "modal": false,
                "destination": {
                    "custom": true,
                    "path": "data/torrents/comics"
                },
                "max": 5,
                "type": "task"
            }
        ],
        "global": {
            "theme": "auto",
            "actions": "all",
            "loading": {
                "enabled": true,
                "threshold": 300
            },
            "task": {
                "progressBar": true,
                "background": true
            },
            "download": {
                "progressBar": true,
                "background": true
            },
            "navbar": {
                "buttons": ["clear", "add", "scrape", "openSynology", "configs", "resume", "pause"]
            },
            "interface": {
                "size": 1,
                "pullToRefresh": true
            }
        },
        "tasks": {
            "clearOnExist": true
        },
        "downloads": {
            "enabled": false,
            "buttons": true,
            "notifications": true,
            "transfer": {
                "erase": true,
                "resume": true,
                "modal": true
            },
            "intercept": {
                "enabled": true,
                "resume": false,
                "erase": true,
                "modal": false,
                "all": false,
                "extensions": [{
                        "ext": ".torrent",
                        "mime": "application/x-bittorrent"
                    }, {
                        "ext": ".flac",
                        "mime": "audio/flac"
                    }, {
                        "ext": ".wav",
                        "mime": "audio/wav"
                    }, {
                        "ext": ".mp3",
                        "mime": "audio/mpeg"
                    }, {
                        "ext": ".aac",
                        "mime": "audio/x-aac"
                    }, {
                        "ext": ".ogg",
                        "mime": "audio/ogg"
                    }, {
                        "ext": ".mp4",
                        "mime": "video/mp4"
                    }, {
                        "ext": ".mpeg",
                        "mime": "video/mpeg"
                    }, {
                        "ext": ".mkv",
                        "mime": "video/x-matroska"
                    }, {
                        "ext": ".7z",
                        "mime": "application/x-7z-compressed"
                    }, {
                        "ext": ".zip",
                        "mime": "application/zip"
                    }, {
                        "ext": ".gz",
                        "mime": "application/gzip"
                    }, {
                        "ext": ".tar",
                        "mime": "application/x-tar"
                    }, {
                        "ext": ".jpeg",
                        "mime": "image/jpeg"
                    }, {
                        "ext": ".jpg",
                        "mime": "image/jpeg"
                    }, {
                        "ext": ".png",
                        "mime": "image/png"
                    }, {
                        "ext": ".svg",
                        "mime": "image/svg+xml"
                    }, {
                        "ext": ".tif",
                        "mime": "image/tiff"
                    }, {
                        "ext": ".gif",
                        "mime": "image/gif"
                    }, {
                        "ext": ".pdf",
                        "mime": "application/pdf"
                    }
                ],
                "active": [{
                        "ext": ".torrent",
                        "mime": "application/x-bittorrent"
                    }
                ]
            }
        },
        "advanced": {
            "logging": {
                "enabled": true,
                "levels": {
                    "background": 4,
                    "content": 4,
                    "popup": 4,
                    "option": 4,
                    "standalone": 4
                },
                "history": false,
                "historyMax": 1000
            }
        },
        "sync": {
            "mode": "sync"
        }
    }
}
```

**Comment by dvcol** [comment]
Hello,

Did it ever work before ?

From what I gather, ed2k links do not pass standard URL sanitization:
![image](https://github.com/user-attachments/assets/02bea895-654d-4c91-a2a7-62ea414fb24f)

So it would require a special handling [here](https://github.com/dvcol/synology-download/blob/be2eb01025e2b1b58e0df43ad44cf73cc21232fb/src/services/http/synology-download2.service.ts#L40-L42)

**Comment by wpigoury** [comment]
Well, yes, I wouldn't send a bug report otherwise :)
I did use it a lot before, and now it doesn't work anymore, I'm guessing due to a Chrome update perhaps.

**Comment by wpigoury** [comment]
Maybe linked to manifest v3?

**Comment by dvcol** [comment]
Possible, but it would be surprising as the manifest spec shouldn't cover what seems to be a change in URL prototype. 

Seems that`|` used to be considered uri safe but not anymore.

I'll manually encode it for now, synology seems to decode all params anyway. 

Hopefully it doesn't have any side efects on other links 🤔 .

**Comment by dvcol** [comment]
I pushed a [new release](https://github.com/dvcol/synology-download/releases/tag/v3.16.3), can you try it to see if it fixes things ?

(I don't really use eMule, so I can't test much beyond test links)

**Comment by wpigoury** [comment]
Updated to 3.16.3 but same issue.
Here's what I have in the console when trying to create a custom task (I just redacted the url but it's a working one):
`[2024-11-04T17:39:09.900Z - popup] Failed to create task {data: {…}, _request: {…}, error: TypeError: Failed to construct 'URL': Invalid URL
    at u (chrome-extension://ebbdkledlkjpgbbmmopg…}data: create_list: falsedestination: custom: falsepath: "data/downloads"[[Prototype]]: Objectextract_password: ""password: ""source: "Custom Task"torrent: ""uri: "ed2k://|file|"username: ""[[Prototype]]: Objecterror: TypeError: Failed to construct 'URL': Invalid URL
    at u (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:114323)
    at s._sanitizeUrl (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:64899)
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:65255
    at Array.map (<anonymous>)
    at s.createTask (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:65245)
    at B.createTask (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:89564)
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:35863
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:36103
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:166713message: "Failed to construct 'URL': Invalid URL"stack: "TypeError: Failed to construct 'URL': Invalid URL\n    at u (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:114323)\n    at s._sanitizeUrl (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:64899)\n    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:65255\n    at Array.map (<anonymous>)\n    at s.createTask (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:65245)\n    at B.createTask (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:89564)\n    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:35863\n    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:36103\n    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/popup.entry.js:242:166713"[[Prototype]]: Error_request: create_list: falsedestination: undefinedextract_password: undefinedpassword: undefinedtorrent: undefinedtype: "url"url: Array(1)0: "ed2k://|file|"length: 1[[Prototype]]: Array(0)username: undefined[[Prototype]]: Object[[Prototype]]: Object
error @ popup.entry.js:242
error @ popup.entry.js:242
error @ popup.entry.js:242
(anonymous) @ popup.entry.js:234
l._error @ popup.entry.js:234
t.error @ popup.entry.js:234
t._error @ popup.entry.js:234
t.error @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._error @ popup.entry.js:234
t.error @ popup.entry.js:234
l._error @ popup.entry.js:234
t.error @ popup.entry.js:234
t._error @ popup.entry.js:234
t.error @ popup.entry.js:234
t._error @ popup.entry.js:234
t.error @ popup.entry.js:234
i @ popup.entry.js:234
e._trySubscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
e._trySubscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
e._trySubscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
l._next @ popup.entry.js:234
t.next @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
e._trySubscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
i @ popup.entry.js:234
e.subscribe @ popup.entry.js:234
(anonymous) @ popup.entry.js:234
o @ popup.entry.js:234
(anonymous) @ popup.entry.js:242
(anonymous) @ popup.entry.js:242
await in (anonymous)
Ve @ popup.entry.js:188
Xe @ popup.entry.js:188
(anonymous) @ popup.entry.js:188
Mr @ popup.entry.js:188
Pr @ popup.entry.js:188
(anonymous) @ popup.entry.js:188
$e @ popup.entry.js:188
(anonymous) @ popup.entry.js:188
Fr @ popup.entry.js:188
Jt @ popup.entry.js:188
Zt @ popup.entry.js:188
t.unstable_runWithPriority @ popup.entry.js:242
qo @ popup.entry.js:188
ze @ popup.entry.js:188
Yt @ popup.entry.js:188Understand this errorAI
popup.entry.js:242 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at u (popup.entry.js:242:114323)
    at s._sanitizeUrl (popup.entry.js:242:64899)
    at popup.entry.js:242:65255
    at Array.map (<anonymous>)
    at s.createTask (popup.entry.js:242:65245)
    at B.createTask (popup.entry.js:242:89564)
    at popup.entry.js:242:35863
    at popup.entry.js:242:36103
    at popup.entry.js:242:166713`

**Comment by dvcol** [comment]
Is this using the last release (v3.16.3) ?

If not, uou might need to force an update in chrome extension page, or manually download the package from github

**Comment by wpigoury** [comment]
It is
![image](https://github.com/user-attachments/assets/09974a64-6896-4f67-beae-20741f643e60)
I even restarted the browser.

**Comment by dvcol** [comment]
Does it throw the same error while using this link ?

```
ed2k://|file|emule0.60a_x64_beta.zip|4069312|A2682308A965960BFB71B37A18905983|h=KJDDEXSC44F323625RJYWJ4IMVIIP55W|/
```

If your not comfortable sharing the link you're using, can you instead describe it's format ?

I beleive, ed2k link should follow this pattern if I'm not mistaken:

```
/^ed2k:\/\/\|file\|[^|]+\|\d+\|[a-fA-F0-9]{32}\|(h=[a-zA-Z0-9]{32}\|)?\/$/
```

**Comment by wpigoury** [comment]
Only difference I saw between your link and the links I'm trying to add is in the file name, in my case it has unencoded square brackets ([ and ]) while spaces are encoded as %20.
This never caused any issue until now but when I manually replace the brackets with %5B and %5D I can add the link.
Not sure why this is happening now, also adding the link with the unencoded square brackets in DownloadStation directly does work without issue.

**Comment by dvcol** [comment]
Um, well I pushed a new version where we skip completely URL validation for emule links and I just encode the whole string.

Hopefully that fixes things, but if not I think it would be better to open an issue on chromium side directly, as it seems to be a broswer change behavior more than anything.

**Comment by wpigoury** [comment]
It looks OK now, thanks.

**Comment by dvcol** [comment]
Awesome :)

If you enjoy the app don't hesitate to leave a review too !
